"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Silk from '@/Backgrounds/Silk/Silk'; // Adjust the import path as needed
import { CartProvider } from '@/components/CartContext'; // Adjust the import path as needed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen bg-black`}
        style={{overflowX: 'hidden'}}
      >
        <div style={{position: 'fixed', inset: 0, zIndex: 0, width: '100vw', height: '100vh', pointerEvents: 'none'}}>
          <Silk
            speed={5}
            scale={1}
            color="#7B7481"
            noiseIntensity={1.5}
            rotation={0}
          />
        </div>
        <div style={{position: 'relative', zIndex: 1, minHeight: '100vh', display: 'flex', flexDirection: 'column'}}>
          <CartProvider>
            <div style={{flex: '1 0 auto'}}>
              {children}
            </div>
          </CartProvider>
        </div>
      </body>
    </html>
  );
}